// AUTO-GENERATED by scripts/embed-templates.mjs. Do not edit by hand.
// Contains base64-encoded report templates shipped inside the bundle so the
// app never performs a fetch() for its official templates.
export type TemplateAsset = { rel: string; bytes: number; base64: string };
export const templates: TemplateAsset[] = [];

export function getTemplate(rel: string): TemplateAsset | undefined {
  return templates.find((t) => t.rel === rel);
}
