import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import { parsePayload } from "@/workers/parseWorker";
import { validateRows } from "@/schema/engine/validate";
import { getDatasetSchema } from "@/schema";
import { isDirectChildOf } from "@/schema/engine/groupChildren";
import { buildHeaderMap } from "@/schema/engine/headerNormalizer";
import { normalizeAoa, coerceFieldValue } from "@/schema/engine/normalize";
import { VHSND_COLUMNS } from "@/schema/columns-vhsnd";
import type { ParsedSheet } from "@/schema/engine/normalize";
import type { Violation } from "@/contracts/violation";

/**
 * Regression coverage for the real-world ODK export shape: a two-row header
 * (human labels above physical codes) with select-multiple parents, one-hot
 * children, 12-hour times, and "not applicable" sentinels.
 *
 * Fixture is generated by scripts/make-shape-sample.mjs with names anonymised.
 */
const SAMPLE = resolve(process.cwd(), "sample-data/DATA_EX_SHAPE.csv");

async function parseShape() {
  const buf = readFileSync(SAMPLE);
  const buffer = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
  return parsePayload({
    buffer,
    fileName: "DATA_EX_SHAPE.csv",
    sizeBytes: buffer.byteLength,
    importedAt: "2026-09-26T00:00:00.000Z",
  });
}

describe("two-row ODK export (DATA_EX_SHAPE.csv)", () => {
  let parsed: ParsedSheet;

  beforeAll(async () => {
    parsed = await parseShape();
  });

  it("treats the code row as a header, not as data", () => {
    expect(parsed.meta.headerRow).toBe(2);
    expect(parsed.rows.length).toBe(3);
    expect(parsed.skippedRows).toBe(0);
  });

  it("keys columns by code so repeated labels stay distinct", () => {
    // The form titles 11 different columns "Others (Specify)".
    const specify = parsed.presentColumns.filter((c) => c.endsWith("_SP"));
    expect(specify).toEqual(
      expect.arrayContaining([
        "A2_SP",
        "A3_SP",
        "C3_SP",
        "C10_SP",
        "C10_1_SP",
        "E3_SP",
        "G3_SP",
        "H1_SP",
        "H2_SP",
        "H4_SP",
        "H32_SP",
      ]),
    );
    expect(specify.length).toBe(11);
  });

  it("keeps one-hot group children as booleans", () => {
    const row = parsed.rows[0].values;
    // Row 1 selects G1 = "A B C E F G H I J".
    const selected = ["A", "B", "C", "E", "F", "G", "H", "I", "J"].map((s) => row[`G1_${s}`]);
    expect(selected).toEqual(Array(9).fill(true));
    expect(row.G1_D).toBeUndefined();
  });

  it("does not let the nested C10_1 group leak into C10", () => {
    expect(isDirectChildOf("C10", "C10_1")).toBe(false);
    expect(isDirectChildOf("C10", "C10_1_A")).toBe(false);
    expect(isDirectChildOf("C10", "C10_A")).toBe(true);
    expect(isDirectChildOf("C10_1", "C10_1_A")).toBe(true);
  });

  it("applies the 12-hour clock to session times", () => {
    const t = parsed.rows.map((r) => [r.values.starttime, r.values.endtime]);
    expect(t).toEqual([
      ["12:55:40", "13:32:33"],
      ["13:56:20", "16:31:48"],
      ["12:38:22", "16:11:21"],
    ]);
  });

  it("reads PNC attendance from H3A_1 and treats H3A as a yes/no", () => {
    const v = parsed.rows.map((r) => [r.values.H3A, r.values.H3A_1, r.values.H3HB1_1]);
    expect(v).toEqual([
      [true, 4, 4],
      [true, 4, 4],
      [true, 7, 6],
    ]);
  });

  it("preserves the 0/1/2 counselling scale", () => {
    const v = parsed.rows.map((r) => [r.values.H33, r.values.H34]);
    expect(v).toEqual([
      [1, 1],
      [1, 1],
      [2, 2],
    ]);
  });

  it("collapses only the duplicate SubmissionDate, and reports it", () => {
    // The code row keeps the 11 "Others (Specify)" columns apart. The export
    // repeats SubmissionDate, so exactly that one is dropped.
    expect(parsed.collapsedColumns).toEqual([
      { label: "SubmissionDate", keptCode: "SubmissionDate", count: 2 },
    ]);
  });

  it("reports instead of silently dropping repeated single-header labels", () => {
    const header = buildHeaderMap();
    const collapsed = normalizeAoa(
      [
        ["Others (Specify)", "Others (Specify)", "Others (Specify)", "Age"],
        ["alpha", "beta", "gamma", "30"],
      ],
      getDatasetSchema("2026.1", "vhsnd").fields,
      {
        fileName: "f.csv",
        sheetName: "S",
        sizeBytes: 0,
        headerRow: 1,
        importedAt: "2026-09-26T00:00:00.000Z",
      },
      header.knownColumns,
      header.normalize,
    );
    expect(collapsed.collapsedColumns).toEqual([
      { label: "Others (Specify)", keptCode: "A2_SP", count: 3 },
    ]);
    expect(collapsed.rows[0].values.A2_SP).toBe("alpha");
  });

  it("reads the ANM 99 sentinel as zero, alongside the real counts", () => {
    // ANM1 names which ANMOL question applies, so 99 means "no data for that
    // question" -- a real zero, not a missing answer.
    const v = parsed.rows.map((r) => [r.values.ANM1, r.values.ANM2, r.values.ANM2_1]);
    expect(v).toEqual([
      [true, 0, undefined],
      [false, 0, undefined],
      [true, 1, 7],
    ]);
  });

  it("never lets the 99 magic number reach a total", () => {
    const total = parsed.rows.reduce(
      (a, r) => a + (typeof r.values.ANM2 === "number" ? r.values.ANM2 : 0),
      0,
    );
    expect(total).toBe(1);
  });

  it("reads a coded answer's Na as missing but keeps a typed NA in a free-text box", () => {
    const fields = getDatasetSchema("2026.1", "vhsnd").fields;
    const byId = new Map(fields.map((f) => [f.id, f]));
    expect(byId.get("H26")!.freeText).toBeFalsy();
    expect(byId.get("B4_2")!.freeText).toBe(true);
    expect(byId.get("remarks")!.freeText).toBe(true);

    // Coded answer: "Na" is the form's "no data" filler.
    expect(coerceFieldValue("text", "Na", byId.get("H26"))).toBeNull();
    // Hand-typed box: "NA" is content somebody entered and must survive.
    expect(coerceFieldValue("text", "NA", byId.get("B4_2"))).toBe("NA");
    expect(coerceFieldValue("text", "NA", byId.get("remarks"))).toBe("NA");
    // A genuinely empty cell is still missing either way.
    expect(coerceFieldValue("text", "  ", byId.get("remarks"))).toBeNull();
  });

  it("drops the Na filler from the fixture's coded fields", () => {
    expect(parsed.rows[0].values.H26).toBeUndefined();
  });

  it("maps the Scan & Share column and drops the duplicate SubmissionDate", () => {
    expect(parsed.rows.map((r) => r.values.New)).toEqual([false, false, false]);
    expect(parsed.presentColumns.filter((c) => c === "SubmissionDate")).toHaveLength(1);
  });

  it("raises no false clinical, sequence or teleconsult violations", () => {
    const schema = getDatasetSchema("2026.1", "vhsnd");
    const { violations } = validateRows(parsed.rows, schema, {
      refDate: "2025-11-19",
      presentColumns: parsed.presentColumns,
    });
    const codes = violations.map((v: Violation) => v.code);
    expect(codes).not.toContain("PNC_SAMPLED_GT_ATTENDED");
    expect(codes).not.toContain("END_BEFORE_START");
    expect(codes).not.toContain("TELECONSULT_DATA_WITHOUT_CONSULT");
    expect(codes).not.toContain("GROUP_OPTION_MISMATCH");
    expect(codes).not.toContain("INVALID_BOOLEAN");
    expect(codes).not.toContain("INVALID_INTEGER");
  });

  it("reads the D option as the declared Hepatitis_B vaccine", () => {
    const schema = getDatasetSchema("2026.1", "vhsnd");
    const { violations } = validateRows(parsed.rows, schema, {
      refDate: "2025-11-19",
      presentColumns: parsed.presentColumns,
    });
    const codes = violations.map((v: Violation) => v.code);
    expect(codes).not.toContain("UNMAPPED_GROUP_OPTION");
  });

  it("surfaces a genuinely unmapped group option instead of hiding it", () => {
    const schema = getDatasetSchema("2026.1", "vhsnd");
    const synthetic = [{ id: "r0", sourceRow: 0, values: { G1: "A Z", G1_A: true } }];
    const { violations } = validateRows(synthetic, schema, {
      refDate: "2025-11-19",
      presentColumns: ["G1", "G1_A"],
    });
    const unmapped = violations.filter((v: Violation) => v.code === "UNMAPPED_GROUP_OPTION");
    expect(unmapped).toHaveLength(1);
    expect(unmapped[0].message).toContain('"Z"');
  });
});
