#!/usr/bin/env node
/**
 * Generates src/schema/columns-vhsnd.ts from data/vhsnd-columns.csv
 * (the official label -> code mapping for the VHSND supervision form).
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";

const inFile = resolve(process.cwd(), "data/vhsnd-columns.csv");
const outFile = resolve(process.cwd(), "src/schema/columns-vhsnd.ts");

const raw = readFileSync(inFile, "utf8");
const lines = raw.split(/\r?\n/).filter((l) => l.trim().length > 0);

function parseLine(line) {
  // Returns [label, code] honoring quoted labels containing commas.
  if (line.startsWith('"')) {
    let inQuotes = true;
    let i = 1;
    let label = "";
    while (i < line.length) {
      const ch = line[i];
      if (inQuotes) {
        if (ch === '"') {
          if (line[i + 1] === '"') {
            label += '"';
            i += 2;
            continue;
          }
          inQuotes = false;
        } else {
          label += ch;
        }
      } else {
        if (ch === ",") {
          const code = line.slice(i + 1).trim();
          return [label, code];
        }
        label += ch;
      }
      i += 1;
    }
    return [label, ""];
  }
  const idx = line.indexOf(",");
  if (idx === -1) return [line.trim(), ""];
  return [line.slice(0, idx).trim(), line.slice(idx + 1).trim()];
}

const seen = new Map();
for (const line of lines) {
  const [label, code] = parseLine(line);
  if (!code) {
    console.warn(`[gen-columns] Skipping row with empty code: "${label}"`);
    continue;
  }
  if (!seen.has(code)) {
    seen.set(code, { code, label: label.length > 0 ? label : code });
  }
}

const entries = [...seen.values()];
entries.sort((a, b) => a.code.localeCompare(b.code, "en", { numeric: true }));

const body = `// AUTO-GENERATED by scripts/gen-columns.mjs from data/vhsnd-columns.csv.
// Do not edit by hand. Each entry is { code, label }: an official column
// (header) and its human-readable question label for the VHSND form.
export type ColumnEntry = { code: string; label: string };

export const VHSND_COLUMNS: ColumnEntry[] = ${JSON.stringify(entries, null, 2)};

export const VHSND_COLUMN_MAP: ReadonlyMap<string, ColumnEntry> = new Map(
  VHSND_COLUMNS.map((c) => [c.code, c]),
);

export function columnLabel(code: string): string {
  return VHSND_COLUMN_MAP.get(code)?.label ?? code;
}
`;

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body, "utf8");
console.log(`[gen-columns] Wrote ${entries.length} columns -> ${outFile}`);