// AUTO-GENERATED by scripts/gen-columns.mjs from data/vhsnd-columns.csv.
// Do not edit by hand. Each entry is { code, label }: an official column
// (header) and its human-readable question label for the VHSND form.
export type ColumnEntry = { code: string; label: string };

export const VHSND_COLUMNS: ColumnEntry[] = [
  {
    "code": "A2",
    "label": "Designation of Supervisor"
  },
  {
    "code": "A2_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "A3",
    "label": "Name of the Institute (Big Bet)"
  },
  {
    "code": "A3_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "ANM1",
    "label": "Is the information being maintained by ANM in the ANMOL App?"
  },
  {
    "code": "ANM2",
    "label": "How many pregnant women are registered in the ANM dashboard of ANMOL App?"
  },
  {
    "code": "ANM2_1",
    "label": "Number of pregnant women"
  },
  {
    "code": "ANM3",
    "label": "How many children below 2 years of age are registered in the ANM dashboard of ANMOL App?"
  },
  {
    "code": "ANM3_1",
    "label": "Number of children under 2 years of age"
  },
  {
    "code": "ANM4",
    "label": "How many target couples (women aged 15 to 49 years) are registered in the ANM dashboard of ANMOL App?"
  },
  {
    "code": "ANM4_1",
    "label": "Number of women aged 15 to 49"
  },
  {
    "code": "ANM5",
    "label": "Are you indenting medicines through DVDMS (e-aushadhi)?"
  },
  {
    "code": "ANM6",
    "label": "Is Enam distributing medicine through DVDMS (e-aushadhi)?"
  },
  {
    "code": "ASHA1",
    "label": "Are Asha workers conducting surveys through the m-ASHA App?"
  },
  {
    "code": "ASHA2",
    "label": "How many families has Asha surveyed through the m-ASHA App?"
  },
  {
    "code": "ASHA2_1",
    "label": "Number of families"
  },
  {
    "code": "ASHA3",
    "label": "Is the Abha-ID of the beneficiaries being created at the session?"
  },
  {
    "code": "ASHA4",
    "label": "Are you (Asha) requesting family planning materials through the FPLMIS app?"
  },
  {
    "code": "ASHA5",
    "label": "Are you (Asha) distributing family planning material through FPLMIS app?"
  },
  {
    "code": "B1",
    "label": "State"
  },
  {
    "code": "B2",
    "label": "District"
  },
  {
    "code": "B2A",
    "label": "Block name"
  },
  {
    "code": "B4",
    "label": "Name of Sub Health Center (HSC/HWC)"
  },
  {
    "code": "B4_1",
    "label": "Name of ANM 1"
  },
  {
    "code": "B4_2",
    "label": "Name of ANM 2"
  },
  {
    "code": "B5",
    "label": "Name of the session venue"
  },
  {
    "code": "B6",
    "label": "AWC Centre Code"
  },
  {
    "code": "B7",
    "label": "Type of session venue"
  },
  {
    "code": "B8",
    "label": "Date of visit"
  },
  {
    "code": "C1",
    "label": "Has the session been held?"
  },
  {
    "code": "C2",
    "label": "Is the session being held at the location shown in the microplan?"
  },
  {
    "code": "C3",
    "label": "If the session has not been held then what is the reason?"
  },
  {
    "code": "C3_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "C4",
    "label": "Which health workers are available at the session site?"
  },
  {
    "code": "C4_A",
    "label": "ANM(1)"
  },
  {
    "code": "C4_B",
    "label": "ANM(2)"
  },
  {
    "code": "C4_C",
    "label": "Hope"
  },
  {
    "code": "C4_D",
    "label": "AWW"
  },
  {
    "code": "C4_E",
    "label": "AWH Assistant"
  },
  {
    "code": "C5",
    "label": "Is the U-WIN portal being used?"
  },
  {
    "code": "C6",
    "label": "Is this session registered on U-WIN"
  },
  {
    "code": "C7",
    "label": "Is the ANM registered on U-WIN?"
  },
  {
    "code": "C8",
    "label": "Are e-vaccination certificates being generated after vaccination?"
  },
  {
    "code": "C9",
    "label": "Is information being stored in the ANMOL App?"
  },
  {
    "code": "C10",
    "label": "Which other members have participated in the session?"
  },
  {
    "code": "C10_1",
    "label": "From whom did you get help regarding preparation or organization at the session venue?"
  },
  {
    "code": "C10_1_88",
    "label": "Others"
  },
  {
    "code": "C10_1_99",
    "label": "nobody"
  },
  {
    "code": "C10_1_A",
    "label": "Members of VHSNC (other than the head)"
  },
  {
    "code": "C10_1_B",
    "label": "Health of Jeevika Village Organization"
  },
  {
    "code": "C10_1_C",
    "label": "Sub-Committee Members"
  },
  {
    "code": "C10_1_D",
    "label": "chief"
  },
  {
    "code": "C10_1_E",
    "label": "PRI (other than Mukhiya)"
  },
  {
    "code": "C10_1_F",
    "label": "NGO"
  },
  {
    "code": "C10_1_G",
    "label": "Volunteer"
  },
  {
    "code": "C10_1_H",
    "label": "Media"
  },
  {
    "code": "C10_1_I",
    "label": "Faith Leader"
  },
  {
    "code": "C10_1_J",
    "label": "SHG"
  },
  {
    "code": "C10_1_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "C10_88",
    "label": "Others"
  },
  {
    "code": "C10_99",
    "label": "nobody"
  },
  {
    "code": "C10_A",
    "label": "Members of VHSNC (other than the head)"
  },
  {
    "code": "C10_B",
    "label": "Health of Jeevika Village Organization"
  },
  {
    "code": "C10_C",
    "label": "Sub-Committee Members"
  },
  {
    "code": "C10_D",
    "label": "chief"
  },
  {
    "code": "C10_E",
    "label": "PRI (other than Mukhiya)"
  },
  {
    "code": "C10_F",
    "label": "NGO"
  },
  {
    "code": "C10_G",
    "label": "Volunteer"
  },
  {
    "code": "C10_H",
    "label": "Media"
  },
  {
    "code": "C10_I",
    "label": "Faith Leader"
  },
  {
    "code": "C10_J",
    "label": "SHG"
  },
  {
    "code": "C10_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "C11",
    "label": "Was the session supervised today by anyone from the Health or Social Welfare Department?"
  },
  {
    "code": "C11_1",
    "label": "Who supervised the session today?"
  },
  {
    "code": "C11_1_88",
    "label": "Others"
  },
  {
    "code": "C11_1_A",
    "label": "Dist. Officials Health"
  },
  {
    "code": "C11_1_B",
    "label": "Dist. Officials ICDs"
  },
  {
    "code": "C11_1_C",
    "label": "MOIC"
  },
  {
    "code": "C11_1_D",
    "label": "MO"
  },
  {
    "code": "C11_1_E",
    "label": "CHO"
  },
  {
    "code": "C11_1_F",
    "label": "BHM"
  },
  {
    "code": "C11_1_G",
    "label": "BCM"
  },
  {
    "code": "C11_1_H",
    "label": "CDPO"
  },
  {
    "code": "C11_1_I",
    "label": "LS"
  },
  {
    "code": "E1",
    "label": "Is the survey register available on Health Day?"
  },
  {
    "code": "E1_1",
    "label": "Have new born babies and new pregnant women been added to the survey register last month?"
  },
  {
    "code": "E2",
    "label": "Is Duelist available on Health Day?"
  },
  {
    "code": "E2_1",
    "label": "How many of these names are of teenagers?"
  },
  {
    "code": "E2_2",
    "label": "How many of these names are of eligible couples?"
  },
  {
    "code": "E2_3",
    "label": "How many women are due for TT-1 vaccination today?"
  },
  {
    "code": "E2_4",
    "label": "How many babies are due for Pentavalent-1 vaccination today?"
  },
  {
    "code": "E2_5",
    "label": "How many women are due for their 3rd/4th antenatal check-up (ANC) today?"
  },
  {
    "code": "E3",
    "label": "Who brought the vaccine and consumables to today's session?"
  },
  {
    "code": "E3_88",
    "label": "Others"
  },
  {
    "code": "E3_A",
    "label": "AVD"
  },
  {
    "code": "E3_B",
    "label": "ANM"
  },
  {
    "code": "E3_C",
    "label": "ASHA"
  },
  {
    "code": "E3_D",
    "label": "AWW"
  },
  {
    "code": "E3_E",
    "label": "Supervisor"
  },
  {
    "code": "E3_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "E4",
    "label": "Is this session more than 1 hour away from the cold chain storage?"
  },
  {
    "code": "endtime",
    "label": "endtime"
  },
  {
    "code": "G1",
    "label": "Which of the following is available at the session site?"
  },
  {
    "code": "G1_A",
    "label": "TD"
  },
  {
    "code": "G1_B",
    "label": "BCG"
  },
  {
    "code": "G1_C",
    "label": "OPV"
  },
  {
    "code": "G1_E",
    "label": "Rotavirus"
  },
  {
    "code": "G1_F",
    "label": "Pneumococcal Conjugate (PCV)"
  },
  {
    "code": "G1_G",
    "label": "IPV"
  },
  {
    "code": "G1_H",
    "label": "Pentavalent"
  },
  {
    "code": "G1_I",
    "label": "MR"
  },
  {
    "code": "G1_J",
    "label": "JE"
  },
  {
    "code": "G1_K",
    "label": "Vit.A"
  },
  {
    "code": "G1_L",
    "label": "DPT"
  },
  {
    "code": "G2",
    "label": "What diluent is available at the session site?"
  },
  {
    "code": "G2_99",
    "label": "No one from above"
  },
  {
    "code": "G2_A",
    "label": "Sodium chloride normal saline"
  },
  {
    "code": "G2_B",
    "label": "Pyrogen free double distilled water"
  },
  {
    "code": "G3",
    "label": "Which of the following is available on the session? (Enter yes only for working machines)"
  },
  {
    "code": "G3_88",
    "label": "Other(specify)"
  },
  {
    "code": "G3_A",
    "label": "working weighing machine for adults"
  },
  {
    "code": "G3_B",
    "label": "working weight machine for children"
  },
  {
    "code": "G3_C",
    "label": "BP machine is working"
  },
  {
    "code": "G3_D",
    "label": "The stethoscope is employed"
  },
  {
    "code": "G3_E",
    "label": "Hemoglobin test kit"
  },
  {
    "code": "G3_F",
    "label": "Glucometer"
  },
  {
    "code": "G3_G",
    "label": "thermometer"
  },
  {
    "code": "G3_H",
    "label": "working infantometer"
  },
  {
    "code": "G3_I",
    "label": "working stadiometer"
  },
  {
    "code": "G3_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "G11",
    "label": "Reference table available to check nutritional status"
  },
  {
    "code": "G12",
    "label": "Which of the following is available on the session? (Enter yes only if you can use it)"
  },
  {
    "code": "G12_A",
    "label": "The IFA's blue pill"
  },
  {
    "code": "G12_B",
    "label": "The IFA's pink pill"
  },
  {
    "code": "G12_C",
    "label": "The IFA's red pill"
  },
  {
    "code": "G12_D",
    "label": "IFA syrup (for adults)"
  },
  {
    "code": "G12_E",
    "label": "IFA Syrup (for children)"
  },
  {
    "code": "G12_F",
    "label": "zinc tablet"
  },
  {
    "code": "G12_G",
    "label": "Zinc syrup"
  },
  {
    "code": "G12_H",
    "label": "Albendazole tablet/syrup"
  },
  {
    "code": "G12_I",
    "label": "calcium tablet"
  },
  {
    "code": "G12_J",
    "label": "Oral contraceptive pill (OCP)"
  },
  {
    "code": "G12_K",
    "label": "Emergency Contraceptive Pill (ECP)"
  },
  {
    "code": "G12_L",
    "label": "condom"
  },
  {
    "code": "G12_M",
    "label": "urinestrip dipstick"
  },
  {
    "code": "G12_N",
    "label": "urine pregnancy kit"
  },
  {
    "code": "G12_O",
    "label": "Antara Injection"
  },
  {
    "code": "G21",
    "label": "Is there adequate space available to ensure the personal privacy of the pregnant woman during ANC?"
  },
  {
    "code": "G24",
    "label": "Soap and water facilities are available"
  },
  {
    "code": "H1",
    "label": "Which of the following services are being provided for prenatal check-up"
  },
  {
    "code": "H1_77",
    "label": "Not applicable"
  },
  {
    "code": "H1_88",
    "label": "Other (specify)"
  },
  {
    "code": "H1_99",
    "label": "none of these"
  },
  {
    "code": "H1_A",
    "label": "Weight measurement"
  },
  {
    "code": "H1_B",
    "label": "Height measurement"
  },
  {
    "code": "H1_C",
    "label": "BP check"
  },
  {
    "code": "H1_D",
    "label": "Hemoglobin test"
  },
  {
    "code": "H1_E",
    "label": "urine test"
  },
  {
    "code": "H1_F",
    "label": "Sugar test"
  },
  {
    "code": "H1_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "H1BP",
    "label": "How many pregnant women's blood pressure did the ANM measure? Observe and enter the number."
  },
  {
    "code": "H1BP1",
    "label": "How many pregnant women did the ANM identify with high blood pressure?"
  },
  {
    "code": "H1HB",
    "label": "How many pregnant women did the ANM take blood samples from to check for anemia? Observe and enter the number."
  },
  {
    "code": "H1HB_2",
    "label": "How many pregnant women with anemia had moderate anemia?"
  },
  {
    "code": "H1HB_3",
    "label": "How many pregnant women with anemia had severe anemia?"
  },
  {
    "code": "H1HB_4",
    "label": "How many pregnant women with anemia were told they had moderate or severe anemia?"
  },
  {
    "code": "H1HB1",
    "label": "How many pregnant women were identified by the ANM as having anemia? Enter the number."
  },
  {
    "code": "H1HB2",
    "label": "How many of the identified women were referred?"
  },
  {
    "code": "H1PB2",
    "label": "How many pregnant women were referred by ANMs who were diagnosed with high blood pressure?"
  },
  {
    "code": "H2",
    "label": "What information is provided during prenatal counselling?"
  },
  {
    "code": "H2_88",
    "label": "Other (specify)"
  },
  {
    "code": "H2_99",
    "label": "none of these"
  },
  {
    "code": "H2_A",
    "label": "Importance of prenatal check-ups"
  },
  {
    "code": "H2_B",
    "label": "Importance of tetanus vaccination"
  },
  {
    "code": "H2_C",
    "label": "Importance of IFA"
  },
  {
    "code": "H2_D",
    "label": "Importance of calcium"
  },
  {
    "code": "H2_E",
    "label": "Information and important advice on danger signs during pregnancy"
  },
  {
    "code": "H2_F",
    "label": "Preparing for childbirth"
  },
  {
    "code": "H2_G",
    "label": "Importance of nutritional supplements"
  },
  {
    "code": "H2_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "H3",
    "label": "What is being done at the VHSND session, post-natal check-up?"
  },
  {
    "code": "H3_77",
    "label": "nine"
  },
  {
    "code": "H3_99",
    "label": "none of these"
  },
  {
    "code": "H3_A",
    "label": "fever check"
  },
  {
    "code": "H3_B",
    "label": "excessive bleeding"
  },
  {
    "code": "H3_C",
    "label": "stomach pain"
  },
  {
    "code": "H3_D",
    "label": "blood test"
  },
  {
    "code": "H3A",
    "label": "How many lactating mothers attended the session for postnatal check-up?"
  },
  {
    "code": "H3A_1",
    "label": "Number"
  },
  {
    "code": "H3HB1_1",
    "label": "How many lactating mothers did the ANM take blood samples to check for anemia? Observe and enter the number."
  },
  {
    "code": "H3HB1_4",
    "label": "How many lactating mothers with anemia were told they had moderate or severe anemia?"
  },
  {
    "code": "H3HB1_5",
    "label": "How many of the identified lactating mothers were referred?"
  },
  {
    "code": "H3HB2_1",
    "label": "How many lactating mothers did the ANM identify as anemic? Enter the number."
  },
  {
    "code": "H3HB3_1",
    "label": "How many of the lactating mothers with anemia had moderate anemia?"
  },
  {
    "code": "H3HB4_1",
    "label": "How many of the lactating mothers with anemia had severe anemia?"
  },
  {
    "code": "H4",
    "label": "What information is provided during postnatal counselling?"
  },
  {
    "code": "H4_88",
    "label": "Other (specify)"
  },
  {
    "code": "H4_99",
    "label": "none of these"
  },
  {
    "code": "H4_A",
    "label": "postpartum hygiene"
  },
  {
    "code": "H4_B",
    "label": "Importance of breastfeeding"
  },
  {
    "code": "H4_C",
    "label": "Information on nutritious food"
  },
  {
    "code": "H4_D",
    "label": "Essential care of the newborn"
  },
  {
    "code": "H4_E",
    "label": "Routine vaccinations"
  },
  {
    "code": "H4_F",
    "label": "Prevention of diarrhea and the importance of ORS"
  },
  {
    "code": "H4_G",
    "label": "Identification and referral of sick children"
  },
  {
    "code": "H4_H",
    "label": "family planning counseling"
  },
  {
    "code": "H4_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "H5",
    "label": "Whether red IFA tablets were distributed"
  },
  {
    "code": "H5_1",
    "label": "Whether delivery was done at the time of antenatal check-up (for pregnant women)"
  },
  {
    "code": "H5_1_1",
    "label": "How many IFA tablets were being given to most pregnant women at one time?"
  },
  {
    "code": "H5_2",
    "label": "Whether red IFA tablets were distributed after delivery (to lactating mothers)"
  },
  {
    "code": "H5_2_1",
    "label": "How many IFA tablets were being given to most lactating mothers at one time?"
  },
  {
    "code": "H6",
    "label": "Are any services provided to the adolescent at the session site?"
  },
  {
    "code": "H6_1",
    "label": "Whether blue IFA tablets were distributed at the session venue"
  },
  {
    "code": "H6_1_1",
    "label": "How many pills are most adolescent girls being given at one time?"
  },
  {
    "code": "H7",
    "label": "Are calcium tablets being distributed at the session site?"
  },
  {
    "code": "H8",
    "label": "Is albendazole being distributed to pregnant women (in the second trimester)?"
  },
  {
    "code": "H9",
    "label": "Are eligible couples present at the session venue as per the due list?"
  },
  {
    "code": "H10",
    "label": "Are OCPs being distributed?"
  },
  {
    "code": "H11",
    "label": "Is ECP being distributed?"
  },
  {
    "code": "H12",
    "label": "Is breastfeeding counseling provided at the session?"
  },
  {
    "code": "H12A",
    "label": "Total number of Antara planted at VHSND site (Ask and observe)"
  },
  {
    "code": "H12B",
    "label": "Did the FLW discuss family planning and its importance with the beneficiaries?"
  },
  {
    "code": "H13",
    "label": "Is the nutritional status of children aged 6 months to 5 years being assessed based on age, weight and length/height?"
  },
  {
    "code": "H14",
    "label": "Are women with danger signs being identified and referred?"
  },
  {
    "code": "H15",
    "label": "Are children with danger signs being identified and referred?"
  },
  {
    "code": "H16",
    "label": "Are the above services being maintained in the MCP card?"
  },
  {
    "code": "H18",
    "label": "Is the ANM cutting the syringe with a hub cutter after use?"
  },
  {
    "code": "H19",
    "label": "If not, the relevant reasons:"
  },
  {
    "code": "H20",
    "label": "Is the ANM writing the date and time of opening on all opened vaccine vials?"
  },
  {
    "code": "H21",
    "label": "Is the vaccinator using the diluted BCG/MR/JE vial after the prescribed period (4 hours)?"
  },
  {
    "code": "H22",
    "label": "Are the 4 important messages being given to parents by the health worker?"
  },
  {
    "code": "H23",
    "label": "Are health workers advising beneficiaries to wait for 30 minutes after vaccination?"
  },
  {
    "code": "H24",
    "label": "Was tele-consultation done at the session site?"
  },
  {
    "code": "H25",
    "label": "How many teleconsultations have been conducted by Spoke?"
  },
  {
    "code": "H26",
    "label": "If there was no consultation, what are the reasons for zero consultation?"
  },
  {
    "code": "H27",
    "label": "Number of teleconsultations you attended during the session"
  },
  {
    "code": "H28",
    "label": "If needed, referral is also being done during teleconsultation."
  },
  {
    "code": "H29",
    "label": "How many new MCP cards are available at the session site?"
  },
  {
    "code": "H30",
    "label": "Were any pregnant women registered today?"
  },
  {
    "code": "H31",
    "label": "Is the information about the services being provided also being maintained in the register?"
  },
  {
    "code": "H32",
    "label": "Which registers are being maintained at the session?"
  },
  {
    "code": "H32_88",
    "label": "Other (specify)"
  },
  {
    "code": "H32_A",
    "label": "RCH Register"
  },
  {
    "code": "H32_B",
    "label": "Rough Register"
  },
  {
    "code": "H32_SP",
    "label": "Others (Specify)"
  },
  {
    "code": "H33",
    "label": "Was the importance of family planning explained to the beneficiaries by the PL/GF during the VHSND visit?"
  },
  {
    "code": "H34",
    "label": "Was the importance of family planning explained to the FLWs by the PL/GF during the VHSND visit?"
  },
  {
    "code": "New",
    "label": "Is Scan & Share available on the session?"
  },
  {
    "code": "remarks",
    "label": "remarks"
  },
  {
    "code": "starttime",
    "label": "starttime"
  },
  {
    "code": "SubmissionDate",
    "label": "SubmissionDate"
  }
];

export const VHSND_COLUMN_MAP: ReadonlyMap<string, ColumnEntry> = new Map(
  VHSND_COLUMNS.map((c) => [c.code, c]),
);

export function columnLabel(code: string): string {
  return VHSND_COLUMN_MAP.get(code)?.label ?? code;
}
